#server:
#  port: 8082
#
#spring:
#  data:
#    mongodb:
#      authentication-database: test2
#      database: test2
#      port: 27017
#      host: localhost
#      auto-index-creation: true
server:
  port: 8020

spring:
  data:
    mongodb:
      authentication-database: admin
#      username: rootuser
#      password: rootpass
      database: test2
      port: 27017
      host: localhost
      auto-index-creation: true